import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    // shadcn's CLI generates imports as "@/components/ui/button" etc. —
    // this is the convention its generated code assumes.
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  // @thing-transfer/proto-gen (frontend/proto-gen/, generated by
  // scripts/codegen_frontend.sh) is CommonJS with no package.json
  // "exports" map, so Vite's dependency crawler doesn't always
  // discover every deep sub-path import ahead of time. Listing them
  // explicitly forces esbuild's CJS->ESM prebundling for each, rather
  // than falling through to serving the raw CJS file (which throws
  // "require is not defined" under native ESM).
  optimizeDeps: {
    include: [
      '@thing-transfer/proto-gen/packagepb/v1/common_pb',
      '@thing-transfer/proto-gen/packagepb/v1/alert_pb',
      '@thing-transfer/proto-gen/packagepb/v1/item_pb',
      '@thing-transfer/proto-gen/packagepb/v1/live_feed_service_pb',
      // Live_feed_serviceServiceClientPb.ts imports live_feed_service_pb
      // via a *relative* path ('../../packagepb/...'), not a bare
      // specifier — Vite's crawler doesn't rewrite relative imports to
      // go through the optimizer, so without listing this entry point
      // explicitly, that relative import reaches the raw CJS file
      // (literal require() calls) directly under native ESM.
      '@thing-transfer/proto-gen/packagepb/v1/Live_feed_serviceServiceClientPb',
      '@thing-transfer/proto-gen/packagepb/v1/query_service_pb',
      // Same relative-import caveat as Live_feed_serviceServiceClientPb above.
      '@thing-transfer/proto-gen/packagepb/v1/Query_serviceServiceClientPb',
    ],
  },
})
