"""Read-only access to the item catalog (data/catalog.db, generated by
scripts/seed_catalog.py). Every service that needs to show a human a
package's contents — not just its package_id — reads through here
instead of querying sqlite directly, so the Item-row-to-proto mapping
lives in exactly one place.
"""

import sqlite3
from pathlib import Path
from typing import Optional

from packagepb.v1 import item_pb2

_DEFAULT_DB_PATH = Path(__file__).resolve().parents[2] / "data" / "catalog.db"


class Catalog:
    def __init__(self, db_path: Path = _DEFAULT_DB_PATH):
        if not db_path.exists():
            raise FileNotFoundError(
                f"catalog db not found at {db_path} — run scripts/seed_catalog.py first"
            )
        self._conn = sqlite3.connect(str(db_path), check_same_thread=False)
        self._conn.row_factory = sqlite3.Row

    def get(self, item_id: str) -> Optional[item_pb2.Item]:
        row = self._conn.execute(
            "SELECT item_id, name, sku, category, unit_weight_kg, stock_quantity, catalog_updated_at "
            "FROM items WHERE item_id = ?",
            (item_id,),
        ).fetchone()
        if row is None:
            return None
        return _row_to_item(row)

    def sample_item_ids(self, n: int) -> list[str]:
        """Random item_ids, for station simulators that need to reference
        real catalog entries instead of made-up ones."""
        rows = self._conn.execute(
            "SELECT item_id FROM items ORDER BY RANDOM() LIMIT ?", (n,)
        ).fetchall()
        return [row["item_id"] for row in rows]

    def close(self) -> None:
        self._conn.close()


def _row_to_item(row: sqlite3.Row) -> item_pb2.Item:
    item = item_pb2.Item(
        item_id=row["item_id"],
        name=row["name"],
        sku=row["sku"],
        category=item_pb2.ItemCategory.Value(row["category"]),
        unit_weight_kg=row["unit_weight_kg"],
        stock_quantity=row["stock_quantity"],
    )
    item.catalog_updated_at.FromJsonString(row["catalog_updated_at"].replace(" ", "T") + "Z")
    return item
